Segmentation faults now prints log for the test case in question

diff --git a/trunk/src/test_dept b/trunk/src/test_dept
--- a/trunk/src/test_dept
+++ b/trunk/src/test_dept
@@ -20,6 +20,8 @@
 TEST_MAINS="${*:-}"
 ERROR_LOG="/tmp/test_dept$$.log"
 
+trap '' 11
+
 run_test() {
   SUITE="$1"
   TEST="$2"
@@ -28,6 +30,7 @@ run_test() {
   if $SUITE $TEST >>$ERROR_LOG 2>&1; then
     printf "."
   else
+    [ "$?" -eq 139 ] && echo "Failure: Segmentation fault" >>$ERROR_LOG
     NUMBER_OF_ERRORS="`expr ${NUMBER_OF_ERRORS:-0} + 1`"
     printf "F"
   fi
@@ -53,5 +56,5 @@ if [ "${NUMBER_OF_ERRORS:-0}" -gt "0" ]; then
   echo
   echo "Failures: ${NUMBER_OF_ERRORS:-0} (of ${NUMBER_OF_TESTS:-0} run tests)."
   sed -n 'H; /^---/ {g; /Failure/p; }; /^+++/h' $ERROR_LOG
-  echo
 fi
+rm -f $ERROR_LOG
