stdout prints in test cases now visible

diff --git a/trunk/src/test_dept b/trunk/src/test_dept
--- a/trunk/src/test_dept
+++ b/trunk/src/test_dept
@@ -20,19 +20,28 @@
 TEST_MAINS="${*:-}"
 ERROR_LOG="/tmp/test_dept$$.log"
 
+trap cleanup 2 4 6
+
+cleanup() {
+    EXITCODE="${1:-2}"
+    rm -f $ERROR_LOG
+    exit $EXITCODE
+}
+
 run_test() {
   SUITE="$1"
   TEST="$2"
-  printf "+++ ${SUITE}, " >>$ERROR_LOG
+  echo "+++ ${SUITE}, ${TEST}: " >&2
   NUMBER_OF_TESTS="`expr ${NUMBER_OF_TESTS:-0} + 1`"
-  if $SUITE $TEST >>$ERROR_LOG 2>&1; then
+  if $SUITE $TEST; then
     printf "."
+    echo "---" >&2
   else
-    [ "$?" -gt 128 ] && echo "Failure: Aborted on signal" >>$ERROR_LOG
+    [ "$?" -gt 128 ] && echo "Failure: Aborted on signal" >&2
     NUMBER_OF_ERRORS="`expr ${NUMBER_OF_ERRORS:-0} + 1`"
     printf "F"
+    echo "-- " >&2
   fi
-  echo "---" >>$ERROR_LOG
 }
 
 if rm -f $ERROR_LOG; then
@@ -45,15 +54,15 @@ fi
 for suite in $TEST_MAINS; do
   suite="`dirname $suite`/`basename $suite`" 
   for test in `$suite`; do
-    run_test "$suite" "$test"
+    run_test "$suite" "$test" 2>>$ERROR_LOG
   done
 done
 echo
 
 if [ "${NUMBER_OF_ERRORS:-0}" -gt "0" ]; then
-  echo
-  echo "Failures: ${NUMBER_OF_ERRORS:-0} (of ${NUMBER_OF_TESTS:-0} run tests)."
-  sed -n 'H; /^---/ {g; /Failure/p; }; /^+++/h' $ERROR_LOG
-  exit 1
+  echo "Failures: ${NUMBER_OF_ERRORS:-0} (of ${NUMBER_OF_TESTS:-0} run tests):"
+  sed -n '/^-- $/{H; g; p; }; H; /^+++/h' $ERROR_LOG
+  cleanup 1
 fi
-rm -f $ERROR_LOG
+
+cleanup 0
